language: ruby
sudo: false
rvm:
  - 2.4.1

matrix:
  include:
    - rvm: jruby-9.1.6.0
    - rvm: 2.3.3
      env: "RAILS_VERSION=5.0.2"
  allow_failures:
    - rvm: jruby-9.1.6.0
  fast_finish: true

env:
 - "RAILS_VERSION=5.1.0"
